apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-material-pass
  namespace: argocd
spec:
  sourceRepos:
    - https://eclipse-tractusx.github.io/charts/dev
  destinations:
    - namespace: product-material-pass
      server: https://kubernetes.default.svc
  roles:
    - name: team-admin
      description: All access to applications inside project-material-pass.
      policies:
        - p, proj:project-material-pass:team-admin, applications, *, project-material-pass/*, allow
        - p, proj:project-material-pass:team-admin, exec, create, project-material-pass/*, allow
      groups:
        - catenax-ng:product-material-pass
    - name: read-only
      description: Read only access to the project
      policies:
        - p, proj:project-material-pass:read-only, applications, get, project-material-pass/*, allow
      groups:
        - catenax-ng:release-management
        - catenax-ng:test-management
