apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-item-relationship-service-frontend
  namespace: argocd
spec:
  sourceRepos:
    - https://eclipse-tractusx.github.io/charts/dev
  destinations:
    - namespace: product-item-relationship-service-frontend
      server: https://kubernetes.default.svc
  roles:
    - name: team-admin
      description: All access to applications inside project-item-relationship-service-frontend.
      policies:
        - p, proj:project-item-relationship-service-frontend:team-admin, applications, *, project-item-relationship-service-frontend/*, allow
        - p, proj:project-item-relationship-service-frontend:team-admin, exec, create, project-item-relationship-service-frontend/*, allow
      groups:
        - catenax-ng:product-item-relationship-service-frontend
    - name: read-only
      description: Read only access to the project
      policies:
        - p, proj:project-item-relationship-service-frontend:read-only, applications, get, project-item-relationship-service-frontend/*, allow
      groups:
        - catenax-ng:release-management
        - catenax-ng:test-management
