apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-essential-services
  namespace: argocd
spec:
  destinations:
    - namespace: product-essential-services
      server: https://kubernetes.default.svc
    - namespace: product-essential-services-pen
      server: https://kubernetes.default.svc
  roles:
    - name: team-admin
      description: All access to applications inside project-essential-services.
      policies:
        - p, proj:product-essential-services:team-admin, applications, *, product-essential-services/*, allow
        - p, proj:product-essential-services:team-admin, exec, create, product-essential-services/*, allow
      groups:
        - catenax-ng:product-essential-services
    - name: read-only
      description: Read only access to the project
      policies:
        - p, proj:project-essential-services:read-only, applications, get, project-essential-services/*, allow
      groups:
        - catenax-ng:release-management
        - catenax-ng:test-management
