apiVersion: v1
kind: Secret
metadata:
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "product-[a-zA-Z0-9\\-]*"
  name: machineuser-pull-secret-ro
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <path:devsecops/data/acme/machine-user#machineuser-pull-secret-ro>
