apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-managed-identity-wallets
  namespace: argocd
spec:
  destinations:
    - namespace: product-managed-identity-wallets
      server: https://kubernetes.default.svc
    - namespace: product-managed-identity-wallets-pen
      server: https://kubernetes.default.svc
  roles:
    - name: team-admin
      description: All access to applications inside project-managed-identity-wallets.
      policies:
        - p, proj:product-managed-identity-wallets:team-admin, applications, *, product-managed-identity-wallets/*, allow
        - p, proj:product-managed-identity-wallets:team-admin, exec, create, product-managed-identity-wallets/*, allow
      groups:
        - catenax-ng:product-managed-identity-wallets
    - name: read-only
      description: Read only access to the project
      policies:
        - p, proj:project-managed-identity-wallets:read-only, applications, get, project-managed-identity-wallets/*, allow
      groups:
        - catenax-ng:release-management
        - catenax-ng:test-management
