apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Product Onboarding
  - ../../argocd/product-example/read-write
  - ../../argocd/product-portal/read-write
  - ../../kyverno/
