apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base-read-only
  - resources/avp-secret.yaml

patchesStrategicMerge:
  - resources/argo-project.yaml
#  - resources/argocd-notifications-cm.yaml
#  - resources/argocd-notifications-secret.yaml
