apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-portal
  namespace: argocd
spec:
  sourceRepos:
    - https://eclipse-tractusx.github.io/charts/dev
  destinations:
    - namespace: product-portal
      server: https://kubernetes.default.svc
    - namespace: product-iam
      server: https://kubernetes.default.svc
  roles:
    - name: team-admin
      description: All access to applications inside project-portal.
      policies:
        - p, proj:project-portal:team-admin, applications, *, project-portal/*, allow
        - p, proj:project-portal:team-admin, exec, create, project-portal/*, allow
      groups:
        - catenax-ng:product-portal
    - name: read-only
      description: Read only access to the project
      policies:
        - p, proj:project-portal:read-only, applications, get, project-portal/*, allow
      groups:
        - catenax-ng:release-management
        - catenax-ng:test-management
