apiVersion: v1
kind: Secret
metadata:
  name: product-behaviour-twin-minio
  namespace: argocd
  annotations:
    avp.kubernetes.io/path: "behaviour-twin-pilot/data/deploy-key"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:catenax-ng/product-behaviour-twin-minio
  name: product-behaviour-twin-minio
  project: project-behaviour-twin-pilot
  sshPrivateKey: |
    <product-behaviour-twin-minio-deploy-key>
