apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Product Onboarding
  - ../../argocd/product-behaviour-twin-pilot/stable
  - ../../argocd/product-bpdm/stable
  - ../../argocd/product-data-format-transformer/stable
  - ../../argocd/product-dft/stable
  - ../../argocd/product-edc/stable
  - ../../argocd/product-essential-services/stable
  - ../../argocd/product-item-relationship-service-frontend/stable
  - ../../argocd/product-knowledge/stable
  - ../../argocd/product-managed-identity-wallets/stable
  - ../../argocd/product-material-pass/stable
  - ../../argocd/product-portal/stable
  - ../../argocd/product-semantics/stable
  - ../../argocd/product-traceability-foss/stable
  - ../../argocd/product-value-added-service/stable

  - helm-repo/eclipse-tractusx-helm-repo.yaml
  - storage-class/standard-ssd-lrs-retain.yaml
#  - pull-secret/secret.yaml

# Kyverno policies (Audit mode)
  - ../../kyverno/policies-audit
