apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-semantics
  namespace: argocd
spec:
  sourceRepos:
    - https://eclipse-tractusx.github.io/charts/dev
  destinations:
    - namespace: product-semantics
      server: https://kubernetes.default.svc
  roles:
    - name: team-admin
      description: All access to applications inside project-semantics.
      policies:
        - p, proj:project-semantics:team-admin, applications, *, project-semantics/*, allow
        - p, proj:project-semantics:team-admin, exec, create, project-semantics/*, allow
      groups:
        - catenax-ng:product-semantics
    - name: read-only
      description: Read only access to the project
      policies:
        - p, proj:project-semantics:read-only, applications, get, project-semantics/*, allow
      groups:
        - catenax-ng:release-management
        - catenax-ng:test-management
