apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: product-dft
  namespace: argocd
spec:
  sourceRepos:
    - https://eclipse-tractusx.github.io/charts/dev
  destinations:
    - namespace: product-dft
      server: https://kubernetes.default.svc
  roles:
    - name: team-admin
      description: All access to applications inside product-dft.
      policies:
        - p, proj:product-dft:team-admin, applications, *, product-dft/*, allow
        - p, proj:product-dft:team-admin, exec, create, product-dft/*, allow
      groups:
        - catenax-ng:product-dft
    - name: read-only
      description: Read only access to the project
      policies:
        - p, proj:product-dft:read-only, applications, get, product-dft/*, allow
      groups:
        - catenax-ng:release-management
        - catenax-ng:test-management
